language: python
dist: bionic
jdk: openjdk11

env:
  matrix:
    - NEO4J_VERSION="3.5.24"
    - NEO4J_VERSION="4.1.4"

before_install:
  - jdk_switcher use openjdk11
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - mkdir -p neo4j-community-$NEO4J_VERSION/data/dbms
  - neo4j-community-$NEO4J_VERSION/bin/neo4j-admin set-initial-password neo4j
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

python:
  - "3.7"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install coveralls
  - python setup.py -q install

script:
  - coverage run --source=grest setup.py test

after_success: coveralls

webhooks:
  urls:
    - https://webhooks.gitter.im/e/29563b0d22ad98eb37c4
  on_success: change
  on_failure: always
  on_start: never
